#!/bin/bash
cd /home/pi/sstv
#./send_aprs &
echo none | sudo tee /sys/class/leds/led0/trigger
echo 1 | sudo tee /sys/class/leds/led0/brightness
#sudo ./camera &


while :
do
	sudo ./send.sh
	sleep 5
done
